// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package tags

import (
	"phihc116/go-task/backend/application/tags"
	"phihc116/go-task/backend/infrastructure/auth"
	"phihc116/go-task/backend/infrastructure/persistence/repositories"
)

// Injectors from wire.go:

func InitializeCreateTagHandler() *tags.CreateTagCommandHandler {
	tagRepo := repositories.NewTagRepoImpl()
	identityService := auth.NewIdentity()
	createTagCommandHandler := tags.NewCreateTagCommandHandler(tagRepo, identityService)
	return createTagCommandHandler
}
